name: cdk deploy

on:
  push:
    # branches:
    #   - develop
    tags:
      - 'v*'
jobs:
  firebase_deploy:
    runs-on: ubuntu-18.04
    steps:
      - name: check connection server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          source: "README.md"
          target: "~/"

      - name: Checkout
        uses: actions/checkout@v1

      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: '10.x'

      - name: Setup firebase CLI
        run: |
          npm install -g firebase-tools

      - name: Setup dependencies
        run: npm install

      - name: Build Code
        run: |
          npm run build.prod

      - name: copy file via ssh password
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          source: "dist"
          target: "/var/www/timble.asia/html"

      


