name: cdk deploy

on:
  push:
    # branches:
    #   - develop
    tags:
      - 'v*'
jobs:
  firebase_deploy:
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: '10.x'

      - name: Setup firebase CLI
        run: |
          npm install -g firebase-tools

      - name: ls -a via ssh
        uses: garygrossgarten/github-action-ssh@release
        with:
          command: ls -a
          host: ${{ secrets.HOST }}
          privateKey: ${{ secrets.PRIVATE_KEY}}

      - name: Setup dependencies
        run: npm install

      - name: Build Code
        run: |
          npm run build.prod

      - name: copy file via ssh password
        uses: garygrossgarten/github-action-scp@release
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          privateKey: ${{ secrets.KEY }}
          local: ./
          remote: ~/

      


